MODEL = "qwen2.5:7b"
DATABASE_URL = "postgresql://postgres:postgres@localhost:5432/multilightest"
MEMORY_TABLE = "trade_memory"
RETRY_THRESHOLD = 0.6
NEWS_LIMIT = 5
PRICE_PERIOD = "7d"
PRICE_INTERVAL = "1d"
USER_AGENT = "Mozilla/5.0"
POS_WORDS = ("beat", "bull", "growth", "gain", "rally", "up", "strong", "surge", "profit")
NEG_WORDS = ("miss", "bear", "loss", "risk", "fall", "drop", "weak", "lawsuit", "cut")
VECTOR_DIM = 3
EVAL_LLM_MODEL = MODEL
EVAL_EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
